name: Build test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: make clean all x64
      run: make -C source clean all
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nesasm_linux_x64
        path: .
    - name: apt update
      run: sudo apt-get update
    - name: Get ARM toolchain
      run: sudo apt-get install gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu
    - name: make clean all arm
      run: make -C source clean all CC=arm-linux-gnueabihf-gcc
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nesasm_linux_arm
        path: .
    - name: make clean all arm64
      run: make -C source clean all CC=aarch64-linux-gnu-gcc
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nesasm_linux_arm64
        path: .

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Install argp
      run: brew install argp-standalone
    - name: Checkout
      uses: actions/checkout@v3
    - name: make clean all
      run: make -C source clean all
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nesasm_macos
        path: .

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          gcc
          git
          libargp-devel
    - name: Checkout
      uses: actions/checkout@v3
    - name: make clean all
      run: make -C source clean all
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nesasm_windows
        path: .
